# Making arrays using numpy 

In [1]:
import numpy as np

## Creating a Single-Dimensional Array 

In [2]:
n1 = np.array([10,20,30,40])

In [3]:
n1

array([10, 20, 30, 40])

In [8]:
type(n1)

numpy.ndarray

## creating a Multy-Dimensional Array 

In [6]:
n2 = np.array([[10,20,30,40],[40,30,20,10]])

In [7]:
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [9]:
type(n2)

numpy.ndarray

## Initialing Numpy array with zeros 

In [14]:
n3 = np.zeros((2,2))
n3

array([[0., 0.],
       [0., 0.]])

In [16]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])