## Vectors (rank 1 tensors) in Numpy 

In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])

In [5]:
x

array([1, 2, 3, 4, 5])

In [6]:
len(x)

5

In [7]:
x.shape

(5,)

In [8]:
type(x)

numpy.ndarray

In [9]:
x[0]  # zero indexed

1

In [10]:
x[2:]

array([3, 4, 5])

In [11]:
type(x[1]) 

numpy.int32

## Vector transposition 

In [12]:
# transposing a regular 1D has no effect
x_t = x.T

In [13]:
x_t.shape

(5,)

In [14]:
y = np.array([[1,2,3]]) # if we add nested matrix style brackets

In [15]:
y.shape

(1, 3)

In [16]:
y_t = y.T
y_t

array([[1],
       [2],
       [3]])

In [17]:
y_t.shape  # Now it has changed

(3, 1)

In [18]:
y__t = y_t.T   #  
y__t

array([[1, 2, 3]])

## Zero vectors 

In [19]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

## Orthogonal Vectors 

In [21]:
i = np.array([1,0])
i

array([1, 0])

In [22]:
j = np.array([0,1])
j

array([0, 1])

In [23]:
np.dot(i,j)

0